# Generated by Django 5.0.4 on 2024-05-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0002_cityevent_journeybusiness_journeycity_userjourney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeybusiness',
            name='business',
        ),
        migrations.RemoveField(
            model_name='journeybusiness',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='journeycity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='journeycity',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='userjourney',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='userjourney',
            name='user',
        ),
        migrations.RemoveField(
            model_name='planning',
            name='activities',
        ),
        migrations.AddField(
            model_name='city',
            name='events',
            field=models.ManyToManyField(related_name='cities', to='messi.event'),
        ),
        migrations.AddField(
            model_name='journey',
            name='businesses',
            field=models.ManyToManyField(related_name='journeys', to='messi.business'),
        ),
        migrations.AddField(
            model_name='journey',
            name='cities',
            field=models.ManyToManyField(related_name='journeys', to='messi.city'),
        ),
        migrations.AddField(
            model_name='planning',
            name='events',
            field=models.ManyToManyField(related_name='plannings', to='messi.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='journeys',
            field=models.ManyToManyField(related_name='users', to='messi.journey'),
        ),
        migrations.DeleteModel(
            name='CityEvent',
        ),
        migrations.DeleteModel(
            name='JourneyBusiness',
        ),
        migrations.DeleteModel(
            name='JourneyCity',
        ),
        migrations.DeleteModel(
            name='UserJourney',
        ),
    ]
