# Generated by Django 5.0.4 on 2024-05-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0003_remove_journeybusiness_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', to='messi.user'),
        ),
    ]
