# Generated by Django 5.0.4 on 2024-05-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messi', '0004_event_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messi.city')),
                ('users', models.ManyToManyField(related_name='groups', to='messi.user')),
            ],
        ),
    ]
